name: auto_test

on:
  push:
    tags:
      - '*'
  pull_request:


jobs:
  auto_test:
    strategy:
      matrix:
        py_ver: ['3.8', '3.9', '3.10', '3.11']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        name: Ensure Python Runtime
        with:
          python-version: ${{matrix.py_ver}}
          architecture: 'x64'
      - name: install pdm
        run: |
          python3 -m pip install pdm
      - name: Install Package
        run: |
          pdm sync
      - name: Test & Report
        run: |
          pdm run test