name: Auto_Test

on:
  push:
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  auto_test:
    strategy:
      matrix:
        py_ver: ['3.10', '3.11']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        name: Ensure Python Runtime
        with:
          python-version: ${{matrix.py_ver}}
          architecture: 'x64'
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          poetry install --no-root
      - name: Test & Report
        run: |
          poetry run pytest --capture=no -v